{{- if and .Values.persistence.enabled .Values.persistence.hostPath (not .Values.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "cds.fullname" . }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  hostPath:
    path: {{ .Values.persistence.hostPath | quote }}
{{- end -}}
