apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "cds.fullname" . }}-hooks
  labels:
    app: {{ template "cds.fullname" . }}-hooks
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "cds.fullname" . }}-hooks
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
      - name: {{ template "cds.fullname" . }}-hooks
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: CDS_CONFIG_FILE
          valueFrom:
            secretKeyRef:
              name: {{ template "cds.fullname" . }}
              key: cds_config_file
        - name: CDS_HOOKS_NAME
          value: '{{ template "cds.fullname" . }}-hooks'
        - name: CDS_HOOKS_URL
          value: 'http://{{ template "cds.fullname" . }}-hooks'
        {{- if .Values.ingress.enabled }}
        - name: CDS_HOOKS_URLPUBLIC
          {{- if .Values.ingress.tls }}
          {{- if .Values.ingress.port }}
          value: 'https://{{.Values.ingress.hostname}}:{{.Values.ingress.port}}/webhooks'
          {{- else }}
          value: 'https://{{.Values.ingress.hostname}}/webhooks'
          {{- end }}
          {{- else }}
          {{- if .Values.ingress.port }}
          value: 'http://{{.Values.ingress.hostname}}:{{.Values.ingress.port}}/webhooks'
          {{- else }}
          value: 'http://{{.Values.ingress.hostname}}/webhooks'
          {{- end }}
          {{- end }}
        {{- end }}
        - name: CDS_HOOKS_UI_HTTP_URL
          value: 'http://{{ template "cds.fullname" . }}-ui'
        - name: CDS_HOOKS_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ template "cds.fullname" . }}
              key: cds-api_auth_sharedinfratoken
        - name: CDS_HOOKS_API_GRPC_URL
          value: 'http://{{ template "cds.fullname" . }}-api:8082'
        - name: CDS_HOOKS_API_HTTP_URL
          value: 'http://{{ template "cds.fullname" . }}-api'
        - name: CDS_HOOKS_CACHE_REDIS_HOST
          value: {{ template "cds.redis.fullname" . }}-master:{{ default "" .Values.redis.master.port }}
        - name: CDS_HOOKS_CACHE_REDIS_PASSWORD
        {{- if .Values.redis.enabled }}
          valueFrom:
            secretKeyRef:
              name: {{ template "cds.redis.fullname" . }}
              key: redis-password #reference postgresql chart secret
        {{- else }}
          value: {{ default "" .Values.redis.password | quote }}
        {{- end }}
        - name: CDS_HOOKS_HTTP_PORT
          value: '8084'
        - name: CDS_LOG_LEVEL
          value: {{ default "" .Values.logLevel | quote }}
        command: ["/bin/sh"]
        args: ["-c", "echo $CDS_CONFIG_FILE | base64 --decode > config.toml && /app/cds-engine-linux-amd64 start hooks --config config.toml"]
        ports:
        - name: http
          containerPort: 8084
