apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cds.fullname" . }}
  labels:
    app: {{ template "cds.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.apiAuthSharedinfratoken }}
  cds-api_auth_sharedinfratoken: {{ default "" .Values.apiAuthSharedinfratoken | b64enc | quote }}
  {{ else }}
  cds-api_auth_sharedinfratoken: {{ randAlphaNum 64 | b64enc | quote }}
  {{ end }}
  {{ if .Values.apiSecretsKey }}
  cds-api_secrets_key: {{ default "" .Values.apiSecretsKey | b64enc | quote }}
  {{ else }}
  cds-api_secrets_key: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
  cds-k8s_config_file: {{ .Files.Get "kubeconfig.yaml" | b64enc | b64enc }}
