apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cds.fullname" . }}-api
  labels:
    app: {{ template "cds.fullname" . }}-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.apiAuthSharedinfratoken }}
  cds-api_auth_sharedinfratoken: {{ default "" .Values.apiAuthSharedinfratoken | b64enc | quote }}
  {{ else }}
  cds-api_auth_sharedinfratoken: {{ randAlphaNum 64 | b64enc | quote }}
  {{ end }}
  {{ if .Values.apiSecretsKey }}
  cds-api_secrets_key: {{ default "" .Values.apiSecretsKey | b64enc | quote }}
  {{ else }}
  cds-api_secrets_key: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
