apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "cds.fullname" . }}-ui
  labels:
    app: {{ template "cds.fullname" . }}-ui
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "cds.fullname" . }}-ui
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
      - name: {{ template "cds.fullname" . }}-ui
        image: "{{ .Values.ui.image.registry }}/{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
          - name: BACKEND_HOST
            value: {{ template "cds.fullname" . }}-api
          - name: BASE_URL
            value: "{{ .Values.ui.baseUrl }}"
          - name: CDS_LOG_LEVEL
            value: "{{ .Values.ui.logLevel }}"
        ports:
        - name: http
          containerPort: 8081
        - name: https
          containerPort: 8081
        livenessProbe:
{{ toYaml .Values.ui.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.ui.readinessProbe | indent 10 }}
        resources:
{{ toYaml .Values.ui.resources | indent 10 }}
